### ISSUE TITLE
Node.js v4 compatibility

### ISSUE THREAD

**Issue by kuy** [bouzuya/beater#7]
Is there any plan to support Node.js v4?
It looks like ES2015 syntax causes errors ([full output](https://travis-ci.org/kuy/console.ws/jobs/138835842)).

```
> console.ws@0.0.1 test /home/travis/build/kuy/console.ws
> beater
/home/travis/build/kuy/console.ws/node_modules/beater-cli/node_modules/beater-cli-reporter/lib/index.js:14
        const passed = results.filter(({ error }) => !!!error);
                                       ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at fs.readdirSync.map.requireReporter (/home/travis/build/kuy/console.ws/node_modules/beater-cli/lib/index.js:35:17)
    at Object.fs.readdirSync.map.requires [as run] (/home/travis/build/kuy/console.ws/node_modules/beater-cli/lib/index.js:56:22)
    at Object.<anonymous> (/home/travis/build/kuy/console.ws/node_modules/beater-cli/bin/beater.sh:3:20)
```

**Comment by bouzuya** [comment]
- [ ] beater
- [ ] beater-cli
- [ ] beater-cli-reporter
- [ ] beater-html-reporter
- [ ] beater-reporter

**Comment by bouzuya** [comment]
fixed
